name: deployment
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest

    environment: release
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true
          fetch-depth: 0
      - name: 安装node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x
      - name: 获取pnpm存储目录
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: 设置pnpm缓存
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: 安装依赖
        run: pnpm install --frozen-lockfile
      - name: 发布npm
        uses: changesets/action@v1
        with:
          publish: pnpm release
          version: pnpm version-packages
          commit: 'chore: publish packages'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
