name: deployment
on:
  push:
    branches:
      - master
jobs:
  deployment:
    # 后期加测试脚本时再用
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    environment: release
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true
          fetch-depth: 0
          node-version: 16.x
          cache: pnpm
      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.x
          store-path: ~/.pnpm-store
      - name: 缓存依赖
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: 安装依赖
        run: pnpm install --frozen-lockfile
      - name: 发布npm
        uses: changesets/action@v1
        with:
          publish: pnpm release
          version: pnpm version-packages
          commit: 'chore: publish packages'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
