name: deployment
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  deployment:
    runs-on: ubuntu-latest

    environment: release
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true
          fetch-depth: 0
      - name: 安装pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: 安装node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: 安装依赖
        run: pnpm install --frozen-lockfile
      - name: 发布npm
        uses: changesets/action@v1
        with:
          publish: pnpm release
          version: pnpm version-packages
          commit: 'chore: publish packages'
        env:
          NPM_CONFIG_PROVENANCE: true
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
